name: Init Repository and Resolve Dynamic Template
on:
  create

jobs:
  init_repo:
    name: Init Repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Define Branch Protection
        run: |
          gh api "repos/${{ github.repository }}/branches/main/protection" --method PUT --input ./github/workflows/init_repo/branch_protection.json
          gh api "repos/${{ github.repository }}/branches/develop/protection" --method PUT --input ./github/workflows/init_repo/branch_protection.json
        env:
          GH_TOKEN: ${{ secrets.PAT_DYNAMIC_TEMPLATE }}
      
      - name: "Manage cnx to internal ${{ vars.ci_report_repo }} repo"
        run: |
          ssh-keygen -t rsa -b 4096 -C "Deployement to ${{ vars.ci_report_repo_path }}" -f deploy-ci-report -N ""
          gh secret set DEPLOY_CI_REPORT_KEY --repo $GITHUB_USER/$PROJECT_NAME < deploy-ci-report
          existing_id=$(gh repo deploy-key list --repo ${{ vars.ci_report_repo_path }} --json id,title --jq ".[] | select(.title | contains(\"${PROJECT_NAME}\")) | .id")
          if [[ -n $existing_id ]]; then # Si la clé est déjà définie
            echo -e "${cBLUE}The Public Key for ${PROJECT_NAME} already exist in ${{ vars.ci_report_repo_path }}, we delete it.${cSTOP}"
            gh repo deploy-key delete $existing_id --repo ${{ vars.ci_report_repo_path }}
          fi
          echo -e "${cGREEN}Save Public Key in $CI_REPORT_PROJECT_PATH.${cSTOP}"
          gh repo deploy-key add deploy-ci-report.pub --repo ${{ vars.ci_report_repo_path }} --allow-write --title "Publication pour ${GITHUB_USER}/${PROJECT_NAME}"
          env:
            GH_TOKEN: ${{ secrets.PAT_DYNAMIC_TEMPLATE }}
      