name: Init Repository and Resolve Dynamic Template
on:
  - create
  - workflow_dispatch # Sometimes the create event does not seem to be fired

jobs:
  init_repo:
    name: Auto Init
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Init Repository
        uses: fletort/init-repo-action@v1
        with:
          repository_deployment: ${{ vars.tpl_deployment_repository }}
          token: ${{ secrets.INIT_TOKEN || secrets.GITHUB_TOKEN }}
          testspace_link_enable: ${{ vars.tpl_testspace_link_enable }}
          testspace_token: ${{ secrets.TESTSPACE_TOKEN }}
          delete_workflow: ${{ vars.tpl_delete_workflow }}
          j2_keep_template: ${{ vars.tpl_j2_keep_template }}
          j2_data_file: ${{ vars.tpl_j2_data_file }}
          j2_data_format: ${{ vars.tpl_j2_data_format }}
          j2_data_url: ${{ vars.tpl_j2_data_url }}
          j2_data_url_format: ${{ vars.tpl_j2_data_url_format }}
          j2_undefined_behaviour: ${{ vars.tpl_j2_undefined_behaviour }}
          base_branch: ${{ vars.tpl_base_branch }}
          branch-before: ${{ vars.tpl_branch_before}}
          branches: ${{ vars.tpl_branches }}
          commit-message: ${{ vars.tpl_commit_message }}
          commit-branch: ${{ vars.tpl_commit_branch }}
          pr-created: ${{ vars.tpl_pr_created }}
          pr-title: ${{ vars.tpl_pr_title }}
          pr-body: ${{ vars.tpl_pr_body }}
